#!/bin/bash


# 不同模块的影响
## 不考虑数据异构
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix query --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix key --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix value --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix attn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix intermediate --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix ffn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 : -n 20 python client.py

# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix query --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix key --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix value --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix attn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix intermediate --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix ffn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 : -n 20 python client.py

# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix query --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix key --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix value --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix attn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix intermediate --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix ffn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 : -n 20 python client.py

# ## 考虑系统异构
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix query --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix key --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix value --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix attn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix intermediate --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix ffn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.02 --enable_sys_heter True : -n 20 python client.py

# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix query --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix key --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix value --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix attn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix intermediate --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 --enable_sys_heter True : -n 20 python client.py
# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix ffn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 0.1 --enable_sys_heter True : -n 20 python client.py

# mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix query --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 --enable_sys_heter True : -n 20 python client.py
mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix key --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 --enable_sys_heter True : -n 20 python client.py
mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix value --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 --enable_sys_heter True : -n 20 python client.py
mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix attn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 --enable_sys_heter True : -n 20 python client.py
mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix intermediate --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 --enable_sys_heter True : -n 20 python client.py
mpiexec -n 1 python server.py --dataset_type sst2 --batch_size 32 --epoch 50 --finetune_type fedlora --fedlora_rank 16 --fedlora_depth 12 --test_target_matrix ffn.output --lr 2e-2 --our_total_rank 192 --data_pattern 0 --partitial_data 1.0 --enable_sys_heter True : -n 20 python client.py

# 考虑数据异构

# 考虑再加一组r = 8的不同模块的实验